"""Generate per-biomarker knowledge chunks from the official spec.

Reads data/biomarkers/biomarkers.json (itself imported from the official
BloodIQ_Biomarker_Specification_v2.xlsx) and writes one retrieval chunk per
biomarker to data/knowledge/kb_biomarkers.md. The KB therefore contains only
curated specification content -- no LLM-generated medical claims.

Run from the project root:
    python -m backend.app.utils.build_kb
"""
import json
from pathlib import Path

from app.utils.paths import project_root


def build_kb() -> Path:
    root = project_root()
    spec = json.loads((root / "data" / "biomarkers" / "biomarkers.json").read_text())
    out = root / "data" / "knowledge" / "kb_biomarkers.md"
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# BloodIQ biomarker knowledge (generated from the official specification)",
        "",
        "Each `##` section is one retrieval chunk. Do not edit this file by",
        "hand; regenerate it with `python -m backend.app.utils.build_kb`.",
        "",
    ]
    for b in spec["biomarkers"]:
        bid = b["biomarker_id"]
        aliases = ", ".join(b.get("common_aliases", []))
        trend = (
            "trend tracking is supported"
            if b.get("supports_trend")
            else "trend tracking is not supported"
        )
        lines += [
            f"## id: kb-bio-{bid.lower()}",
            f"## title: {b['standard_name']}",
            f"## biomarker_id: {bid}",
            f"## category: {b.get('category', '')}",
            f"{b['standard_name']} ({bid}) is a {b.get('category', 'laboratory')}",
            f"biomarker. Also known as: {aliases}." if aliases else "",
            f"What it measures: {b.get('description', 'Not specified.')}",
            f"Typical unit: {b.get('typical_units', 'as reported')}.",
            f"Measurement: {b.get('calculation_type', 'Direct measurement')};",
            f"{trend}.",
            f"Handling note: {b.get('special_handling', '')}".rstrip(),
            "",
        ]
    out.write_text("\n".join(line for line in lines if line is not None))
    print(f"Wrote {len(spec['biomarkers'])} biomarker chunks to {out}")
    return out


if __name__ == "__main__":
    build_kb()
